apiVersion: v1
kind: Service
metadata:
  name: hostname-svc-clusterip
  namespace: production
spec:
  selector:
    app: webserver
  ports:
  - port: 8080
    targetPort: 80
    name: web-port
  type: ClusterIP